name: Build site

on:
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            out
            .next
          key: ${{ runner.os }}-build-${{ hashFiles('out') }}
          restore-keys: ${{ runner.os }}-build-

      - name: Install dependencies
        run: bun install

      - name: Static HTML export
        run: bun run build

      - name: Upload archive
        uses: actions/upload-artifact@v4
        with:
          name: export
          path: ./out